name: Hello World
on: 

   push:
     branches:
      - main
      - devops
   pull_request:
    branches:
     - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build my command
      run: echo "i builded"
    
